/* generated from webui/index.html by the Makefile, do not edit */
#ifndef VOSTOK_WEBUI_PAGE
#define VOSTOK_WEBUI_PAGE
static const char WEBUI_INDEX_HTML[] =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>Vostok Radio - DSP control</title>\n"
"<style>\n"
":root{\n"
"  --bg:#0e1116;\n"
"  --panel:#161b22;\n"
"  --panel2:#1b222c;\n"
"  --line:#2a323d;\n"
"  --text:#dbe3ec;\n"
"  --dim:#8b98a8;\n"
"  --accent:#4aa3ff;\n"
"  --ok:#3fb950;\n"
"  --warn:#d29922;\n"
"  --hot:#f85149;\n"
"  --mpx:#a371f7;\n"
"}\n"
"*{box-sizing:border-box}\n"
"html,body{margin:0;padding:0}\n"
"body{\n"
"  background:var(--bg);\n"
"  color:var(--text);\n"
"  font:14px/1.45 ui-sans-serif,system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;\n"
"  -webkit-font-smoothing:antialiased;\n"
"}\n"
"header{\n"
"  position:sticky;top:0;z-index:20;\n"
"  display:flex;align-items:center;gap:14px;flex-wrap:wrap;\n"
"  padding:10px 16px;\n"
"  background:rgba(14,17,22,.92);\n"
"  backdrop-filter:blur(8px);\n"
"  border-bottom:1px solid var(--line);\n"
"}\n"
"h1{font-size:15px;margin:0;font-weight:600;letter-spacing:.02em;white-space:nowrap}\n"
"h1 span{color:var(--dim);font-weight:400}\n"
".spacer{flex:1}\n"
".dot{width:9px;height:9px;border-radius:50%;background:var(--hot);display:inline-block;margin-right:6px}\n"
".dot.on{background:var(--ok);box-shadow:0 0 8px rgba(63,185,80,.6)}\n"
".status{color:var(--dim);font-size:12px;white-space:nowrap}\n"
"button{\n"
"  font:inherit;font-size:13px;\n"
"  background:var(--panel2);color:var(--text);\n"
"  border:1px solid var(--line);border-radius:6px;\n"
"  padding:6px 12px;cursor:pointer;\n"
"}\n"
"button:hover{border-color:#41505f}\n"
"button.primary{background:#12395f;border-color:#1d5c99}\n"
"button.primary:hover{background:#164a7c}\n"
"button.danger:hover{border-color:var(--hot);color:var(--hot)}\n"
"button:disabled{opacity:.5;cursor:default}\n"
"input[type=text],input[type=number],input[type=search]{\n"
"  font:inherit;background:#0b0e13;color:var(--text);\n"
"  border:1px solid var(--line);border-radius:5px;padding:4px 7px;\n"
"}\n"
"input:focus,button:focus-visible{outline:2px solid var(--accent);outline-offset:1px}\n"
"\n"
"main{padding:16px;max-width:1500px;margin:0 auto}\n"
".card{\n"
"  background:var(--panel);border:1px solid var(--line);\n"
"  border-radius:10px;margin-bottom:16px;overflow:hidden;\n"
"}\n"
".card>h2{\n"
"  font-size:13px;margin:0;padding:10px 14px;\n"
"  text-transform:uppercase;letter-spacing:.09em;color:var(--dim);\n"
"  border-bottom:1px solid var(--line);background:var(--panel2);\n"
"}\n"
".card .body{padding:6px 14px 12px}\n"
"\n"
"/* meters */\n"
"#meters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;padding:14px}\n"
".meter{min-width:0}\n"
".meter .cap{display:flex;justify-content:space-between;font-size:11px;color:var(--dim);margin-bottom:4px}\n"
".meter .cap b{color:var(--text);font-weight:500;font-variant-numeric:tabular-nums}\n"
".bar{height:9px;border-radius:5px;background:#0b0e13;border:1px solid var(--line);overflow:hidden}\n"
".bar>i{display:block;height:100%;width:0%;background:linear-gradient(90deg,#2f81f7,#3fb950 55%,#d29922 82%,#f85149);transition:width .12s linear}\n"
".bar.solo>i{background:var(--accent)}\n"
"\n"
"/* controls */\n"
".rows{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:2px 22px}\n"
"/* minmax(0,..) on every track, otherwise a long label cannot shrink below its\n"
"   own content and pushes straight through the slider next to it */\n"
".row{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,1fr) 88px;align-items:center;gap:12px;padding:5px 0;border-bottom:1px solid #1d242e}\n"
".row:last-child{border-bottom:0}\n"
".row>*{min-width:0}\n"
".row label{font-size:13px;color:var(--text);display:flex;align-items:center;gap:6px;min-width:0}\n"
".row label .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
".row label .u{color:var(--dim);font-size:11px;flex:none}\n"
".row .num{width:100%;text-align:right;font-variant-numeric:tabular-nums}\n"
".row .wide{grid-column:2 / span 2;min-width:0}\n"
".row .wide input{width:100%}\n"
"input[type=range]{display:block;width:100%;min-width:0;accent-color:var(--accent);background:transparent;height:20px;margin:0}\n"
"/* one control per line once there is no room for label and slider side by side */\n"
"@media (max-width:560px){\n"
"  .rows{grid-template-columns:1fr}\n"
"  .row{grid-template-columns:1fr 88px}\n"
"  .row label{grid-column:1 / span 2}\n"
"  .row .wide{grid-column:1 / span 2}\n"
"}\n"
".badge{\n"
"  font-size:9px;letter-spacing:.06em;text-transform:uppercase;\n"
"  border:1px solid;border-radius:4px;padding:0 4px;line-height:14px;flex:none;\n"
"}\n"
".badge.rebuild{color:var(--warn);border-color:#5c4813}\n"
".badge.restart{color:var(--hot);border-color:#6b2b28}\n"
".badge.mpxcache{color:var(--mpx);border-color:#4a3172}\n"
"\n"
"/* switch */\n"
".sw{position:relative;display:inline-block;width:38px;height:20px;flex:none;cursor:pointer;vertical-align:middle}\n"
".sw input{position:absolute;opacity:0;width:100%;height:100%;margin:0;cursor:pointer}\n"
"/* the track is painted over the checkbox, it must not eat the click */\n"
".sw i{position:absolute;inset:0;pointer-events:none;background:#0b0e13;border:1px solid var(--line);border-radius:20px;transition:.15s}\n"
".sw i::after{content:\"\";position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;background:var(--dim);transition:.15s}\n"
".sw input:checked+i{background:#123a22;border-color:#2c6b3f}\n"
".sw input:checked+i::after{left:20px;background:var(--ok)}\n"
".sw input:focus-visible+i{outline:2px solid var(--accent);outline-offset:1px}\n"
"\n"
"/* band table */\n"
".scroll{overflow-x:auto}\n"
"table{border-collapse:collapse;width:100%;font-size:13px}\n"
"th,td{padding:4px 8px;text-align:center;border-bottom:1px solid #1d242e;white-space:nowrap}\n"
"th.rowhead,td.rowhead{\n"
"  text-align:left;position:sticky;left:0;background:var(--panel);z-index:2;\n"
"  border-right:1px solid var(--line);\n"
"}\n"
"thead th{color:var(--dim);font-weight:500;font-size:11px;text-transform:uppercase;letter-spacing:.06em;background:var(--panel2)}\n"
"thead th.rowhead{background:var(--panel2)}\n"
"td input[type=number]{width:82px;text-align:right;font-variant-numeric:tabular-nums}\n"
"tbody tr:hover td{background:#1a212b}\n"
"tbody tr:hover td.rowhead{background:#1a212b}\n"
".bandlevel{height:4px;background:#0b0e13;border-radius:3px;margin-top:3px;overflow:hidden}\n"
".bandlevel>i{display:block;height:100%;width:0;background:var(--accent);transition:width .12s linear}\n"
"\n"
"/* status lines for the stream player and the sound card */\n"
".state{display:flex;align-items:center;gap:8px;font-size:12.5px;color:var(--dim);\n"
"  padding:8px 10px;margin-top:8px;background:#12171e;border:1px solid var(--line);border-radius:7px}\n"
".state .led{width:8px;height:8px;border-radius:50%;background:var(--dim);flex:none}\n"
".state.playing .led{background:var(--ok);box-shadow:0 0 8px rgba(63,185,80,.6)}\n"
".state.playing{color:var(--text)}\n"
".state.starting .led{background:var(--warn)}\n"
".state.failed .led{background:var(--hot)}\n"
".state.failed{color:#ffb3ae}\n"
"#audiostate{margin:0 0 14px}\n"
"\n"
"#toast{\n"
"  position:fixed;left:50%;bottom:22px;transform:translateX(-50%) translateY(20px);\n"
"  background:#1f2732;border:1px solid var(--line);border-radius:8px;\n"
"  padding:9px 16px;font-size:13px;opacity:0;pointer-events:none;transition:.2s;z-index:50;\n"
"  box-shadow:0 8px 24px rgba(0,0,0,.5);\n"
"}\n"
"#toast.show{opacity:1;transform:translateX(-50%) translateY(0)}\n"
"#toast.err{border-color:var(--hot);color:#ffb3ae}\n"
".hint{color:var(--dim);font-size:12px;padding:0 14px 12px;margin:0}\n"
".hidden{display:none !important}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<header>\n"
"  <h1>Vostok Radio <span>/ dsp control</span></h1>\n"
"  <span class=\"status\"><span id=\"live\" class=\"dot\"></span><span id=\"livetext\">connecting</span></span>\n"
"  <span class=\"status\" id=\"loadtext\"></span>\n"
"  <div class=\"spacer\"></div>\n"
"  <input type=\"search\" id=\"filter\" placeholder=\"filter settings\" style=\"width:170px\">\n"
"  <button id=\"btn-save\" class=\"primary\">Save</button>\n"
"  <button id=\"btn-load\">Reload file</button>\n"
"  <button id=\"btn-restart\" class=\"danger\">Restart</button>\n"
"</header>\n"
"\n"
"<main>\n"
"  <div class=\"state\" id=\"audiostate\"><span class=\"led\"></span><span id=\"audiotext\">connecting</span></div>\n"
"  <div class=\"card\">\n"
"    <h2>Levels</h2>\n"
"    <div id=\"meters\"></div>\n"
"  </div>\n"
"  <div id=\"groups\"></div>\n"
"  <p class=\"hint\" id=\"footer\"></p>\n"
"</main>\n"
"\n"
"<div id=\"toast\"></div>\n"
"\n"
"<script>\n"
"\"use strict\";\n"
"\n"
"var schema=null, values=null, nbands=7, configPath=\"\";\n"
"var pending={}, flushTimer=null, needsReload=false;\n"
"\n"
"function el(tag,cls,text){\n"
"  var e=document.createElement(tag);\n"
"  if(cls) e.className=cls;\n"
"  if(text!=null) e.textContent=text;\n"
"  return e;\n"
"}\n"
"function qs(id){ return document.getElementById(id); }\n"
"\n"
"var toastTimer=null;\n"
"function toast(msg,isErr){\n"
"  var t=qs(\"toast\");\n"
"  t.textContent=msg;\n"
"  t.className=\"show\"+(isErr?\" err\":\"\");\n"
"  clearTimeout(toastTimer);\n"
"  toastTimer=setTimeout(function(){ t.className=\"\"; },2600);\n"
"}\n"
"\n"
"function getJSON(url){\n"
"  return fetch(url,{cache:\"no-store\"}).then(function(r){\n"
"    if(!r.ok) throw new Error(r.status+\" \"+r.statusText);\n"
"    return r.json();\n"
"  });\n"
"}\n"
"function post(url,body){\n"
"  return fetch(url,{\n"
"    method:\"POST\",\n"
"    headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},\n"
"    body:body||\"\"\n"
"  }).then(function(r){ return r.json().catch(function(){ return {}; }); });\n"
"}\n"
"\n"
"/* ---------------------------------------------------------------- sliders */\n"
"/* parameters like the band release span five decades, a linear slider is\n"
"   useless there so those get a logarithmic one */\n"
"function isLog(p){ return p.min>0 && p.max/p.min>=500; }\n"
"var SLIDER_STEPS=1000;\n"
"\n"
"function toSlider(p,v){\n"
"  if(isNaN(v)) v=p.min;\n"
"  if(v<p.min) v=p.min;\n"
"  if(v>p.max) v=p.max;\n"
"  if(isLog(p)){\n"
"    var lo=Math.log(p.min), hi=Math.log(p.max);\n"
"    return Math.round((Math.log(v)-lo)/(hi-lo)*SLIDER_STEPS);\n"
"  }\n"
"  return Math.round((v-p.min)/(p.max-p.min)*SLIDER_STEPS);\n"
"}\n"
"function fromSlider(p,x){\n"
"  var f=x/SLIDER_STEPS, v;\n"
"  if(isLog(p)){\n"
"    var lo=Math.log(p.min), hi=Math.log(p.max);\n"
"    v=Math.exp(lo+f*(hi-lo));\n"
"  }else{\n"
"    v=p.min+f*(p.max-p.min);\n"
"  }\n"
"  if(p.type==\"int\") return Math.round(v);\n"
"  /* snap to something a human can read back */\n"
"  var mag=Math.max(Math.abs(v),1e-12);\n"
"  var digits=Math.max(3,Math.min(10,4-Math.floor(Math.log(mag)/Math.LN10)));\n"
"  return parseFloat(v.toPrecision(digits));\n"
"}\n"
"function fmt(p,v){\n"
"  if(p.type==\"int\") return String(v);\n"
"  if(v===0) return \"0\";\n"
"  var a=Math.abs(v);\n"
"  if(a<0.001||a>=1e6) return v.toExponential(2);\n"
"  return String(parseFloat(v.toPrecision(6)));\n"
"}\n"
"\n"
"/* ------------------------------------------------------------- write path */\n"
"function queueSet(name,value){\n"
"  pending[name]=String(value);\n"
"  if(!flushTimer) flushTimer=setTimeout(flush,120);\n"
"}\n"
"function flush(){\n"
"  flushTimer=null;\n"
"  var body=[],keys=Object.keys(pending);\n"
"  if(!keys.length) return;\n"
"  for(var i=0;i<keys.length;i++)\n"
"    body.push(encodeURIComponent(keys[i])+\"=\"+encodeURIComponent(pending[keys[i]]));\n"
"\n"
"  var touchedBands=(keys.indexOf(\"mb.bands\")>=0);\n"
"  pending={};\n"
"  post(\"/api/set\",body.join(\"&\")).then(function(r){\n"
"    if(r && (r.unknown||r.invalid))\n"
"      toast(\"rejected: \"+(r.first_error||\"unknown setting\"),true);\n"
"    if(touchedBands) reload();\n"
"  }).catch(function(e){ toast(\"write failed: \"+e.message,true); });\n"
"}\n"
"\n"
"/* --------------------------------------------------------------- controls */\n"
"function makeBadge(p){\n"
"  if(p.apply==\"live\") return null;\n"
"  var b=el(\"span\",\"badge \"+p.apply,p.apply==\"mpxcache\"?\"cache\":p.apply);\n"
"  b.title=p.apply==\"rebuild\" ? \"rebuilds the filters, expect a short click\"\n"
"        : p.apply==\"mpxcache\" ? \"regenerates the mpx wave cache, audio drops for a moment\"\n"
"        : \"takes effect after a restart\";\n"
"  return b;\n"
"}\n"
"\n"
"function boolControl(p,index,initial){\n"
"  //a label, so a click anywhere on the switch reaches the checkbox inside it\n"
"  var wrap=el(\"label\",\"sw\");\n"
"  var cb=el(\"input\");\n"
"  cb.type=\"checkbox\";\n"
"  cb.checked=!!initial;\n"
"  cb.addEventListener(\"change\",function(){\n"
"    queueSet(index==null?p.name:p.name+\"[\"+index+\"]\",cb.checked?1:0);\n"
"  });\n"
"  wrap.appendChild(cb);\n"
"  wrap.appendChild(el(\"i\"));\n"
"  return wrap;\n"
"}\n"
"\n"
"function numberBox(p,index,initial,onlyBox){\n"
"  var box=el(\"input\",\"num\");\n"
"  box.type=\"number\";\n"
"  box.step=\"any\";\n"
"  box.value=fmt(p,initial);\n"
"  box.title=p.help;\n"
"\n"
"  var slider=null;\n"
"  if(!onlyBox){\n"
"    slider=el(\"input\");\n"
"    slider.type=\"range\";\n"
"    slider.min=0;\n"
"    slider.max=SLIDER_STEPS;\n"
"    slider.step=1;\n"
"    slider.value=toSlider(p,initial);\n"
"    slider.title=p.help;\n"
"  }\n"
"\n"
"  var key=(index==null?p.name:p.name+\"[\"+index+\"]\");\n"
"\n"
"  function push(v){ queueSet(key,v); }\n"
"\n"
"  if(slider){\n"
"    slider.addEventListener(\"input\",function(){\n"
"      var v=fromSlider(p,parseFloat(slider.value));\n"
"      box.value=fmt(p,v);\n"
"      push(v);\n"
"    });\n"
"  }\n"
"  box.addEventListener(\"change\",function(){\n"
"    var v=parseFloat(box.value);\n"
"    if(isNaN(v)){ box.value=fmt(p,p.min); v=p.min; }\n"
"    if(v<p.min) v=p.min;\n"
"    if(v>p.max) v=p.max;\n"
"    if(p.type==\"int\") v=Math.round(v);\n"
"    box.value=fmt(p,v);\n"
"    if(slider) slider.value=toSlider(p,v);\n"
"    push(v);\n"
"  });\n"
"\n"
"  return {box:box,slider:slider};\n"
"}\n"
"\n"
"function textControl(p,initial){\n"
"  var t=el(\"input\");\n"
"  t.type=\"text\";\n"
"  t.value=initial==null?\"\":initial;\n"
"  t.title=p.help;\n"
"  t.style.width=\"100%\";\n"
"  t.addEventListener(\"change\",function(){ queueSet(p.name,t.value); });\n"
"  return t;\n"
"}\n"
"\n"
"function scalarRow(p){\n"
"  var row=el(\"div\",\"row\");\n"
"  row.dataset.search=(p.name+\" \"+p.label+\" \"+p.group).toLowerCase();\n"
"\n"
"  var lab=el(\"label\");\n"
"  lab.appendChild(el(\"span\",\"name\",p.label));\n"
"  if(p.unit) lab.appendChild(el(\"span\",\"u\",p.unit));\n"
"  var badge=makeBadge(p);\n"
"  if(badge) lab.appendChild(badge);\n"
"  lab.title=p.name+\" - \"+p.help;\n"
"  row.appendChild(lab);\n"
"\n"
"  var v=values[p.name];\n"
"  if(p.type==\"bool\"){\n"
"    var mid=el(\"div\");\n"
"    mid.appendChild(boolControl(p,null,v));\n"
"    row.appendChild(mid);\n"
"    row.appendChild(el(\"span\"));\n"
"  }else if(p.type==\"string\"){\n"
"    var cell=el(\"div\",\"wide\");\n"
"    cell.appendChild(textControl(p,v));\n"
"    row.appendChild(cell);\n"
"  }else{\n"
"    var c=numberBox(p,null,v,false);\n"
"    var holder=el(\"div\");\n"
"    holder.appendChild(c.slider);\n"
"    row.appendChild(holder);\n"
"    row.appendChild(c.box);\n"
"  }\n"
"  return row;\n"
"}\n"
"\n"
"function bandTable(params){\n"
"  var wrap=el(\"div\",\"scroll\");\n"
"  var table=el(\"table\");\n"
"\n"
"  var thead=el(\"thead\");\n"
"  var hr=el(\"tr\");\n"
"  hr.appendChild(el(\"th\",\"rowhead\",\"band\"));\n"
"  for(var i=0;i<nbands;i++){\n"
"    var th=el(\"th\",null,String(i+1));\n"
"    var f=values[\"band.freq\"][i];\n"
"    th.appendChild(el(\"div\",\"u\"));\n"
"    th.lastChild.style.fontSize=\"10px\";\n"
"    th.lastChild.style.color=\"var(--dim)\";\n"
"    th.lastChild.textContent=(f>=1000?(f/1000)+\"k\":f)+\"Hz\";\n"
"    var lv=el(\"div\",\"bandlevel\");\n"
"    lv.appendChild(el(\"i\"));\n"
"    lv.id=\"bandlevel\"+i;\n"
"    th.appendChild(lv);\n"
"    hr.appendChild(th);\n"
"  }\n"
"  thead.appendChild(hr);\n"
"  table.appendChild(thead);\n"
"\n"
"  var tbody=el(\"tbody\");\n"
"  for(var k=0;k<params.length;k++){\n"
"    var p=params[k];\n"
"    var tr=el(\"tr\");\n"
"    tr.dataset.search=(p.name+\" \"+p.label).toLowerCase();\n"
"\n"
"    var head=el(\"td\",\"rowhead\");\n"
"    head.appendChild(el(\"span\",null,p.label));\n"
"    if(p.unit) head.appendChild(el(\"span\",\"u\",\" \"+p.unit));\n"
"    var badge=makeBadge(p);\n"
"    if(badge){ head.appendChild(document.createTextNode(\" \")); head.appendChild(badge); }\n"
"    head.title=p.name+\" - \"+p.help;\n"
"    tr.appendChild(head);\n"
"\n"
"    for(var b=0;b<nbands;b++){\n"
"      var td=el(\"td\");\n"
"      if(p.type==\"bool\"){\n"
"        td.appendChild(boolControl(p,b,values[p.name][b]));\n"
"      }else{\n"
"        td.appendChild(numberBox(p,b,values[p.name][b],true).box);\n"
"      }\n"
"      tr.appendChild(td);\n"
"    }\n"
"    tbody.appendChild(tr);\n"
"  }\n"
"  table.appendChild(tbody);\n"
"  wrap.appendChild(table);\n"
"  return wrap;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------ meters */\n"
"var METERS=[\n"
"  [\"pre_agc\",\"before agc\"],\n"
"  [\"post_agc\",\"after agc\"],\n"
"  [\"pre_clip\",\"before clipper\"],\n"
"  [\"post_clip\",\"after clipper\"],\n"
"  [\"distortion\",\"clipper activity\"]\n"
"];\n"
"\n"
"function buildMeters(){\n"
"  var host=qs(\"meters\");\n"
"  host.textContent=\"\";\n"
"  for(var i=0;i<METERS.length;i++){\n"
"    var m=el(\"div\",\"meter\");\n"
"    var cap=el(\"div\",\"cap\");\n"
"    cap.appendChild(el(\"span\",null,METERS[i][1]));\n"
"    var val=el(\"b\",\"\",\"-\");\n"
"    val.id=\"mv_\"+METERS[i][0];\n"
"    cap.appendChild(val);\n"
"    m.appendChild(cap);\n"
"    var bar=el(\"div\",\"bar\"+(METERS[i][0]==\"distortion\"?\" solo\":\"\"));\n"
"    var fill=el(\"i\");\n"
"    fill.id=\"mb_\"+METERS[i][0];\n"
"    bar.appendChild(fill);\n"
"    m.appendChild(bar);\n"
"    host.appendChild(m);\n"
"  }\n"
"}\n"
"\n"
"function dbPercent(v){\n"
"  if(!(v>0)) return 0;\n"
"  var db=20*Math.log(v/32767)/Math.LN10;\n"
"  var pct=(db+60)/60*100;\n"
"  return Math.max(0,Math.min(100,pct));\n"
"}\n"
"\n"
"function drawMeters(m){\n"
"  for(var i=0;i<4;i++){\n"
"    var key=METERS[i][0], v=m[key]||0;\n"
"    qs(\"mb_\"+key).style.width=dbPercent(v).toFixed(1)+\"%\";\n"
"    var db=v>0?20*Math.log(v/32767)/Math.LN10:-99;\n"
"    qs(\"mv_\"+key).textContent=(db<=-99?\"-inf\":db.toFixed(1))+\" dB\";\n"
"  }\n"
"  var d=m.distortion||0;\n"
"  qs(\"mb_distortion\").style.width=Math.min(100,d*20).toFixed(1)+\"%\";\n"
"  qs(\"mv_distortion\").textContent=d.toFixed(2)+\" %\";\n"
"\n"
"  if(m.band_level){\n"
"    for(var b=0;b<m.band_level.length;b++){\n"
"      var node=qs(\"bandlevel\"+b);\n"
"      if(node) node.firstChild.style.width=dbPercent(Math.abs(m.band_level[b])).toFixed(1)+\"%\";\n"
"    }\n"
"  }\n"
"  setText(\"loadtext\",m.running?(\"dsp load \"+(m.load||0).toFixed(0)+\"%\"):\"\");\n"
"\n"
"  /* a missing node must not stop the rest of the meters from updating */\n"
"  if(m.audio){\n"
"    setText(\"audiotext\",m.audio.ok\n"
"      ? (\"sound card: \"+m.audio.text)\n"
"      : (\"no audio: \"+m.audio.text+\" - retrying every 3s, you can change the device below\"));\n"
"    setClass(\"audiostate\",\"state \"+(m.audio.ok?\"playing\":\"failed\"));\n"
"  }\n"
"\n"
"  var stateNames=[\"off\",\"starting\",\"playing\",\"failed\"];\n"
"  if(m.source){\n"
"    setText(\"srctext\",m.source.text);\n"
"    setClass(\"srcstate\",\"state \"+(stateNames[m.source.state]||\"off\"));\n"
"  }\n"
"\n"
"  if(m.rds){\n"
"    setText(\"rdstext\",m.rds.text);\n"
"    var cls=m.rds.on?\"playing\":(m.rds.text==\"off\"?\"off\":\"failed\");\n"
"    setClass(\"rdsstate\",\"state \"+cls);\n"
"  }\n"
"}\n"
"\n"
"function setText(id,text){\n"
"  var n=qs(id);\n"
"  if(n) n.textContent=text;\n"
"}\n"
"function setClass(id,cls){\n"
"  var n=qs(id);\n"
"  if(n) n.className=cls;\n"
"}\n"
"\n"
"function statusLine(prefix){\n"
"  var st=el(\"div\",\"state\");\n"
"  st.id=prefix+\"state\";\n"
"  st.appendChild(el(\"span\",\"led\"));\n"
"  var txt=el(\"span\",null,\"...\");\n"
"  txt.id=prefix+\"text\";\n"
"  st.appendChild(txt);\n"
"  return st;\n"
"}\n"
"\n"
"/* -------------------------------------------------------------- rendering */\n"
"function render(){\n"
"  var host=qs(\"groups\");\n"
"  host.textContent=\"\";\n"
"\n"
"  var order=[], byGroup={};\n"
"  for(var i=0;i<schema.params.length;i++){\n"
"    var p=schema.params[i];\n"
"    if(!byGroup[p.group]){ byGroup[p.group]=[]; order.push(p.group); }\n"
"    byGroup[p.group].push(p);\n"
"  }\n"
"\n"
"  for(var g=0;g<order.length;g++){\n"
"    var name=order[g], list=byGroup[name];\n"
"    var card=el(\"div\",\"card\");\n"
"    card.appendChild(el(\"h2\",null,name));\n"
"    var body=el(\"div\",\"body\");\n"
"\n"
"    if(list[0].band){\n"
"      body.appendChild(bandTable(list));\n"
"    }else{\n"
"      var rows=el(\"div\",\"rows\");\n"
"      for(var k=0;k<list.length;k++) rows.appendChild(scalarRow(list[k]));\n"
"      body.appendChild(rows);\n"
"    }\n"
"\n"
"    /* the stream player and the rds encoder both report back */\n"
"    if(name==\"Stream source\") body.appendChild(statusLine(\"src\"));\n"
"    if(name==\"RDS\") body.appendChild(statusLine(\"rds\"));\n"
"\n"
"    card.appendChild(body);\n"
"    host.appendChild(card);\n"
"  }\n"
"  applyFilter();\n"
"}\n"
"\n"
"function applyFilter(){\n"
"  var q=qs(\"filter\").value.trim().toLowerCase();\n"
"  var nodes=document.querySelectorAll(\"[data-search]\");\n"
"  for(var i=0;i<nodes.length;i++){\n"
"    var hit=(q==\"\" || nodes[i].dataset.search.indexOf(q)>=0);\n"
"    nodes[i].classList.toggle(\"hidden\",!hit);\n"
"  }\n"
"  var cards=document.querySelectorAll(\"#groups .card\");\n"
"  for(var c=0;c<cards.length;c++){\n"
"    var any=cards[c].querySelectorAll(\"[data-search]:not(.hidden)\").length>0;\n"
"    cards[c].classList.toggle(\"hidden\",!any);\n"
"  }\n"
"}\n"
"\n"
"function reload(){\n"
"  return getJSON(\"/api/state\").then(function(s){\n"
"    values=s.values;\n"
"    nbands=s.nbands;\n"
"    render();\n"
"  });\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------- boot */\n"
"function boot(){\n"
"  buildMeters();\n"
"  getJSON(\"/api/schema\").then(function(s){\n"
"    schema=s;\n"
"    configPath=s.config;\n"
"    qs(\"footer\").textContent=\"settings file: \"+configPath+\n"
"      \"  -  live changes apply on the next audio buffer, they are only kept across restarts if you press Save\";\n"
"    return reload();\n"
"  }).then(function(){\n"
"    setInterval(poll,250);\n"
"    poll();\n"
"  }).catch(function(e){\n"
"    toast(\"cannot talk to the processor: \"+e.message,true);\n"
"  });\n"
"}\n"
"\n"
"var offlineCount=0;\n"
"function poll(){\n"
"  getJSON(\"/api/meters\").then(function(m){\n"
"    offlineCount=0;\n"
"    qs(\"live\").className=\"dot on\";\n"
"    qs(\"livetext\").textContent=\"connected\";\n"
"    drawMeters(m);\n"
"  }).catch(function(){\n"
"    offlineCount++;\n"
"    if(offlineCount>1){\n"
"      qs(\"live\").className=\"dot\";\n"
"      qs(\"livetext\").textContent=\"offline\";\n"
"    }\n"
"  });\n"
"}\n"
"\n"
"qs(\"filter\").addEventListener(\"input\",applyFilter);\n"
"\n"
"qs(\"btn-save\").addEventListener(\"click\",function(){\n"
"  post(\"/api/save\").then(function(r){\n"
"    if(r.ok) toast(\"saved to \"+r.path);\n"
"    else toast(\"save failed: \"+(r.error||\"unknown\"),true);\n"
"  });\n"
"});\n"
"\n"
"qs(\"btn-load\").addEventListener(\"click\",function(){\n"
"  post(\"/api/load\").then(function(r){\n"
"    if(r.ok){ toast(\"loaded \"+r.applied+\" settings from \"+r.path); reload(); }\n"
"    else toast(\"load failed: \"+(r.error||\"unknown\"),true);\n"
"  });\n"
"});\n"
"\n"
"qs(\"btn-restart\").addEventListener(\"click\",function(){\n"
"  if(!confirm(\"Save the settings and restart the processor?\\nAudio stops for a second or two.\")) return;\n"
"  post(\"/api/restart\").then(function(){\n"
"    toast(\"restarting\");\n"
"    qs(\"live\").className=\"dot\";\n"
"    qs(\"livetext\").textContent=\"restarting\";\n"
"    var tries=0;\n"
"    var t=setInterval(function(){\n"
"      tries++;\n"
"      getJSON(\"/api/state\").then(function(){\n"
"        clearInterval(t);\n"
"        reload().then(function(){ toast(\"processor is back\"); });\n"
"      }).catch(function(){\n"
"        if(tries>40){ clearInterval(t); toast(\"the processor did not come back\",true); }\n"
"      });\n"
"    },700);\n"
"  });\n"
"});\n"
"\n"
"boot();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
#endif
